development:
  url: 'http://localhost:8080/jasperserver/'
  username: 'jasperadmin'
  password: 'jasperadmin'

test:
  url: 'http://server:port/jasperserver/'
  username: 'username'
  password: 'password'

production:
  url: 'http://server:port/jasperserver/'
  username: 'username'
  password: 'password'
